packages:
  - fimidara-server-node
  - fimidara-nextjs
  - fimidara-js-sdk
  - fimidara-private-js-sdk
allowBuilds:
  argon2: true
  core-js: true
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - argon2
  - core-js
  - esbuild
  - msw
  - sharp
  - sqlite3
  - unrs-resolver
